### ISSUE TITLE
Please send expected output for sysmon using test-config.xml on windows 10

### ISSUE THREAD

**Issue by qonyo** [qonyo/VDI_Wazuh_Sysmon#10]
as the title said, this is for testing purposes

**Comment by usmcseal911** [comment]
![image](https://user-images.githubusercontent.com/55080674/169659167-b293092d-c3e2-4e39-8296-5bbbd38cf0a4.png)

Config yang di test adalah _hashfile_. 

![image](https://user-images.githubusercontent.com/55080674/169659441-79d2f076-5f13-4688-bef8-9b2826584f39.png)

hasilnya kita bisa lihat di gambar menunjukkan bahwa Hashing Algorithm berubah hanya menunjukkan SHA256
