### ISSUE TITLE
Please send expected output for sysmon using test-config.xml on windows 7

### ISSUE THREAD

**Issue by qonyo** [qonyo/VDI_Wazuh_Sysmon#11]

**Comment by usmcseal911** [comment]
![image](https://user-images.githubusercontent.com/55080674/169660579-1fda529e-7f1f-4655-80f1-bea91081c1e8.png)
Config yang di test adalah _hashfile_.

![image](https://user-images.githubusercontent.com/55080674/169660520-fbecf390-a3c7-4fd8-a074-e9f7c17631cd.png)
hasilnya kita bisa lihat di gambar menunjukkan bahwa Hashing Algorithm berubah hanya menunjukkan SHA256 pada **sysmon** _windows 7_
